name: Push File

on: [pull_request]

env:
    sha: $GITHUB_SHA

jobs:
  copy-file:
    runs-on: ubuntu-latest
    env:
      dest_repo: 'WoHal/just-test'
      user_email: 'socianerr@gmail.com'
      user_name: 'WoHal'
      dest_folder: 'copy_file_test_github_action'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Mark test file
      run: |-
        echo $GITHUB_SHA > test02.md
        echo $GITHUB_SHA > test03.md
        echo $GITHUB_SHA > test04.md
        echo $GITHUB_SHA > test05.md

    - name: Ignore unchanged file
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test01.md'
        destination_repo: ${{ env.dest_repo }}
        user_email: ${{ env.user_email }}
        user_name: ${{ env.user_name }}
        destination_folder: ${{ env.dest_folder }}

    - name: Push changed file
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test02.md'
        destination_repo: ${{ env.dest_repo }}
        user_email: ${{ env.user_email }}
        user_name: ${{ env.user_name }}
        destination_folder: ${{ env.dest_folder }}

    - name: Check custom commit message
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test03.md'
        destination_repo: ${{ env.dest_repo }}
        user_email: ${{ env.user_email }}
        user_name: ${{ env.user_name }}
        destination_folder: ${{ env.dest_folder }}
        commit_message: 'A custom message.'

    - name: Check rsync runs
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test04.md'
        destination_repo: ${{ env.dest_repo }}
        user_email: ${{ env.user_email }}
        user_name: ${{ env.user_name }}
        destination_folder: ${{ env.dest_folder }}
        use_rsync: 'true'

    - name: Push renamed file
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test02.md'
        destination_repo: ${{ env.dest_repo }}
        user_email: ${{ env.user_email }}
        user_name: ${{ env.user_name }}
        destination_folder: ${{ env.dest_folder }}
        rename: 'test02_rename.md'

    - name: Clean
      uses: ./
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'test05.md'
        destination_repo: ${{ env.dest_repo }}
        user_email: ${{ env.user_email }}
        user_name: ${{ env.user_name }}
        destination_folder: ${{ env.dest_folder }}
        clean_folder: 'true'
